#!/usr/bin/env bash

_git_topics() {
  local commands="
    finish help integrate list reintegrate release review setup start
  "
  local command="$(__git_find_on_cmdline "$commands")"

  if test -z "$command"; then
    __gitcomp "$commands"
    return
  fi

  case "$command" in
    finish) __git_topics_finish ;;
    help) __git_topics_help ;;
    integrate) __git_topics_integrate ;;
    list) __git_topics_list ;;
    reintegrate) __git_topics_reintegrate ;;
    release) __git_topics_release ;;
    review) __git_topics_review ;;
    setup) __git_topics_setup ;;
    start) __git_topics_start ;;
    *) COMPREPLY=() ;;
  esac
}

__git_topics_finish() {
  __gitcomp "$(
    __git topics list --all --porcelain | grep '^+' | sed 's/^+ //'
  )"
}

__git_topics_help() {
  __gitcomp "
    finish help integrate list reintegrate release review setup start
    management
  "
}

__git_topics_integrate() {
  __gitcomp "$(
    __git topics list --all --porcelain | grep '^-' | sed 's/^- //'
  )"
}

__git_topics_list() {
  __gitcomp "--all --remote --short --porcelain"
}

__git_topics_reintegrate() {
  __git_find_repo_path
  if test -d "$__git_repo_path/git-topics-reintegrate"; then
    __gitcomp "--continue --skip --abort --quit --edit-todo"
    return
  fi
  case "$cur" in
    --*) __gitcomp "--onto" ;;
    *) __git_complete_refs ;;
  esac
}

__git_topics_release() {
  __gitcomp "major minor patch"
}

__git_topics_review() {
  __gitcomp "$(
    __git topics list --all --porcelain | grep '^-' | sed 's/^- //'
  )"
}

__git_topics_setup() {
  case "$cur" in
    --*) __gitcomp "--force" ;;
  esac
}

__git_topics_start() {
  __git_complete_refs
}
