#!/usr/bin/env bash

OPTIONS="<topic>"

if test "$#" != 1; then
  usage
fi

require_setup
require_clean_work_tree "finish git topic"
set_topic "$1"

keep_up_to_date "$TOPIC"

keep_up_to_date "$DEVELOP"

if ! git merge-base --is-ancestor "$TOPIC" "$DEVELOP"; then
  echo >&2 "Branch $TOPIC has not been merged to $DEVELOP."
  echo >&2 "Use 'git topics integrate $TOPIC' first and try again."
  exit 1
fi

keep_up_to_date "$MASTER"

if ! git merge-base --is-ancestor "$TOPIC" "$MASTER"; then
  git checkout --quiet "$MASTER"
  git merge --no-ff "$TOPIC"
fi
