#!/usr/bin/env bash

OPTIONS_SPEC="\
$dashless $command [<command>]
--
"

eval "$(parsed_options "$@")"

while test -n "$1"; do
  case "$1" in
    --) shift; break ;;
    *) shift ;;
  esac
done

case "$#" in
  0) man git-topics ;;
  1) man "git-topics-$1" ;;
  *) usage ;;
esac
