#!/usr/bin/env bash

OPTIONS_SPEC="\
$dashless $command <topic>
--
"

eval "$(parsed_options "$@")"

require_setup
require_topic "$@"
require_clean_work_tree "integrate git topic"

keep_up_to_date "$TOPIC"
keep_up_to_date "$DEVELOP"
git checkout --quiet "$DEVELOP"
git merge --no-ff "$TOPIC"
