#!/usr/bin/env bash

OPTIONS_SPEC="\
$dashless $command <topic>
--
"

eval "$(parsed_options "$@")"

while test -n "$1"; do
  case "$1" in
    --) shift; break ;;
    *) shift ;;
  esac
done

if test "$#" -ne 1; then
  usage
fi

require_setup
keep_up_to_date "$MASTER"
git checkout -b "$1" "$MASTER"
