#!/usr/bin/env bash

usage() {
  echo >&2 "usage: git topics help [<command>]"
  echo >&2
  echo >&2 "See 'git topics help help'."
  exit 1
}

case "$#" in
  0) man git-topics ;;
  1) man "git-topics-$1" ;;
  *) usage ;;
esac
