#!/usr/bin/env bash

usage() {
  echo >&2 "usage: git topics stage <topic>"
  echo >&2
  echo >&2 "See 'git topics help stage'."
  exit 1
}

if test $# != 1; then
  usage
fi

require_setup
require_clean_work_tree "stage git topic"
set_topic "$1"

keep_up_to_date "$DEVELOP"
git checkout "$DEVELOP"
git merge --no-ff "$TOPIC"
